# Generated by Django 3.2.9 on 2021-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.CharField(max_length=100000),
        ),
    ]
