# Generated by Django 3.2.7 on 2021-11-16 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dish_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=2)]),
        ),
    ]
