# Generated by Django 3.2.9 on 2021-11-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cartitem_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish'),
        ),
    ]
